# Generated by Django 4.2.17 on 2025-03-12 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role_rename_adult_adultprofile_childprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childprofile',
            name='parent',
        ),
        migrations.AddField(
            model_name='childprofile',
            name='guiding_adult',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.adultprofile'),
            preserve_default=False,
        ),
    ]
