# Generated by Django 4.2.17 on 2025-03-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_childprofile_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childprofile',
            name='exercise_language',
        ),
    ]
