# Generated by Django 4.2.17 on 2025-03-13 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_childprofile_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('language', models.CharField(choices=[('en', 'English')], default='en', max_length=50)),
                ('avg_score', models.FloatField()),
                ('count_apperances', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_text', models.CharField()),
                ('submitted_text', models.CharField()),
                ('uploaded_image', models.ImageField(upload_to='')),
                ('score', models.FloatField()),
                ('level', models.CharField(choices=[('letters', 'Letters'), ('words', 'Words'), ('category', 'Category')], default='letters', max_length=50)),
                ('language', models.CharField(choices=[('en', 'English')], default='en', max_length=50)),
                ('category', models.CharField(choices=[('vehicle', 'Vehicle'), ('animal', 'Animal')], max_length=50)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('time_taken', models.DurationField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.childprofile')),
            ],
        ),
    ]
