# Generated by Django 4.2.17 on 2025-03-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisesubmission',
            name='language',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='language',
        ),
    ]
