# Generated by Django 4.2.17 on 2025-03-29 16:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_childprofile_exercise_language'),
        ('exercises', '0003_remove_exercisesubmission_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_text', models.CharField()),
                ('submitted_text', models.CharField()),
                ('submitted_image', models.ImageField(upload_to='')),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('level', models.CharField(choices=[('letters', 'Letters'), ('words', 'Words'), ('category', 'Category')], default='letters', max_length=50)),
                ('category', models.CharField(choices=[('vehicle', 'Vehicle'), ('animal', 'Animal')], max_length=50)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('submission_date', models.DateTimeField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.childprofile')),
            ],
        ),
        migrations.AlterField(
            model_name='letter',
            name='avg_score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.DeleteModel(
            name='ExerciseSubmission',
        ),
    ]
