# Generated by Django 4.2.17 on 2025-03-29 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercise_alter_letter_avg_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='score',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
