# Generated by Django 4.2.17 on 2025-03-29 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_alter_exercise_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='submitted_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
