# Generated by Django 4.2.17 on 2025-03-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_alter_exercise_score_alter_exercise_submission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('vehicle', 'Vehicle'), ('animal', 'Animal'), ('color', 'Color'), ('toy', 'Toy')], max_length=50),
        ),
    ]
