# Generated by Django 4.2.17 on 2025-04-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_alter_exercise_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='child',
            new_name='child_id',
        ),
        migrations.RenameField(
            model_name='letter',
            old_name='count_apperances',
            new_name='count_appearances',
        ),
    ]
