# Generated by Django 4.2.17 on 2025-04-04 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_rename_child_exercise_child_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='child_id',
            new_name='child',
        ),
    ]
