# Generated by Django 4.2.17 on 2025-04-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_rename_child_id_exercise_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(blank=True, choices=[('vehicle', 'Vehicle'), ('animal', 'Animal'), ('color', 'Color'), ('toy', 'Toy')], max_length=50, null=True),
        ),
    ]
