# Generated by Django 4.2.17 on 2025-05-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_alter_exercise_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
