# Generated by Django 4.2.17 on 2025-05-20 14:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_exercise_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_letter', models.CharField(max_length=1)),
                ('expected_letter', models.CharField(max_length=1)),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('position', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
            ],
        ),
        migrations.DeleteModel(
            name='Letter',
        ),
    ]
