# Generated by Django 4.2.17 on 2025-05-20 14:40

import django.core.validators
from django.db import migrations
import exercises.models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0013_alter_exercise_score_alter_submittedletter_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='score',
            field=exercises.models.ScoreRoundingDecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='submittedletter',
            name='score',
            field=exercises.models.ScoreRoundingDecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
