# Generated by Django 4.2.17 on 2025-06-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0014_alter_exercise_score_alter_submittedletter_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorizedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('vehicle', 'Vehicle'), ('animal', 'Animal'), ('color', 'Color'), ('toy', 'Toy'), ('food', 'Food'), ('clothing', 'Clothing'), ('action', 'Action'), ('job', 'Job'), ('nature', 'Nature'), ('family', 'Family'), ('place', 'Place')], db_index=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(blank=True, choices=[('vehicle', 'Vehicle'), ('animal', 'Animal'), ('color', 'Color'), ('toy', 'Toy'), ('food', 'Food'), ('clothing', 'Clothing'), ('action', 'Action'), ('job', 'Job'), ('nature', 'Nature'), ('family', 'Family'), ('place', 'Place')], max_length=50, null=True),
        ),
    ]
